#测试环境
spring: 
  profiles: test
  
server:
  port: 8060
  
---
#开发环境
spring: 
  profiles: dev

server:
  port: 7060
---

logging: 
  level: 
    com.springboot.sms: debug
  
spring:
  profiles:
    active: dev
  application:
    name: smsDevice

#########################################################    
#配置说明： 渠道相互保护作用									#
#priority 优先级，1》2》3....								#
#channelName 渠道名称：汉语全拼 ,目前支持[xuanwu/wangjian]	#
#status 默认是有效：1- used,2- unused						#  
#########################################################
sms:
  channels:
    - sendUrl: http://211.147.239.62:9050/cgi-bin/sendsms
      userName: xxx
      password: ******
      priority: 2 
      channelName: xuanwu
    - sendUrl: http://utf8.sms.webchinese.cn/
      userName: xxx
      password: ******
      priority: 1
      channelName: wangjian
      status: 1

