spring: 
  profiles: test
  
server:
  port: 8060
---
spring: 
  profiles: dev

server:
  port: 7060
---

logging: 
  level: 
    com.springboot.sms: debug
  
spring:
  profiles:
    active: dev
  application:
    name: smsDevice

sms:
  channels:
    - sendUrl: http://211.147.239.62:9050/cgi-bin/sendsms
      userName: CQCYWJ@CQCYWJ
      password: NVgyRx7N
      priority: 2 
      channelName: xuanwu
    - sendUrl: http://211.147.239.62:9050/cgi-bin/sendsms
      userName: yx@sijiankeji1
      password: 456789
      priority: 1
      channelName: xuanwu
  
#http:
#  #最大连接数
#  maxTotal: 100
#  #并发数
#  defaultMaxPerRoute: 20
#  #创建连接的最长时间
#  connectTimeout: 1000
#  #从连接池中获取到连接的最长时间
#  connectionRequestTimeout: 500
#  #数据传输的最长时间
#  socketTimeout: 10000
#  #提交请求前测试连接是否可用
#  staleConnectionCheckEnabled: true
